### PR TITLE
fix(ui-tasks): filter deleted studies jobs

### LINKED ISSUE #1470: Presence of tasks from a deleted study in the task view.
## Description
When you delete a study that has tasks and these are still present in the application's tasks page, the name of the study no longer appears in the list. Instead we have the Unknown name followed by the study ID.

And when you click on it to be redirected to this study that has been deleted, we have an empty page that grinds and returns nothing.

## Possible Solution
As a solution, after deleting the study, remove all of its tasks from the tasks page. or again, if one clicks on a task called Unknown (study id) the user receives a message informing them that the study no longer exists (because it has been deleted).
And when you click on it to be redirected to this study that has been deleted, we have a black page that grinds and returns nothing.

## Screenshot
image

## Environment

- [x] Production
- [x] Staging
- [x] Desktop

### PR DESCRIPTION
**Pull request by hdinia**
fixes #1470

### CODE REVIEW

File: webapp/src/services/api/study.ts [hunk 1]
```diff
@@ -329,17 +329,18 @@ export const mapLaunchJobDTO = (j: LaunchJobDTO): LaunchJob => ({
...
   latest = false,
 ): Promise<LaunchJob[]> => {
-  let query = sid
-    ? `?study=${sid}&filter_orphans=${filterOrphans}`
-    : `?filter_orphans=${filterOrphans}`;
-  if (latest) {
-    query += "&latest=100";
-  }
-  const res = await client.get(`/v1/launcher/jobs${query}`);
+  const queryParams = new URLSearchParams({
```
Comment (skamril) [inline webapp/src/services/api/study.ts]:
```javascript
const queryParams = new URLSearchParams([
  ["filter_orphans", filterOrphans],
  studyId && ["study", studyId],
  latest && ["latest", 100],
].filter(Boolean));
```

**Review by skamril — CHANGES_REQUESTED** [review]

File: webapp/src/services/api/study.ts (hunk 1 above)
Comment (hdinia) [reply webapp/src/services/api/study.ts]: Thanks but it causes TS issues, I let you see

Comment (hdinia) [reply webapp/src/services/api/study.ts]: I think it would be this instead: (which is the same as my solution)
```javascript
const queryParams = new URLSearchParams(
  [
    ["filter_orphans", String(filterOrphans)],
    ...(studyId ? [["study", studyId]] : []),
    ...(latest ? [["latest", "100"]] : []),
  ]
);
```

Comment (skamril) [reply webapp/src/services/api/study.ts]:
```javascript
const queryParams = new URLSearchParams(
    R.filter(Boolean, {
      filter_orphans: filterOrphans,
      study: studyId,
      latest: latest && 100,
    }),
  );
```

File: webapp/src/services/api/study.ts [hunk 2]
```diff
@@ -329,19 +330,21 @@ export const mapLaunchJobDTO = (j: LaunchJobDTO): LaunchJob => ({
...
-    : `?filter_orphans=${filterOrphans}`;
-  if (latest) {
-    query += "&latest=100";
-  }
-  const res = await client.get(`/v1/launcher/jobs${query}`);
-  const data = await res.data;
-  return data.map(mapLaunchJobDTO);
+  const queryParams = new URLSearchParams(
+    R.filter(Boolean, {
+      filter_orphans: filterOrphans.toString(),
```
Comment (skamril) [inline webapp/src/services/api/study.ts]:
```javascript
filter_orphans: filterOrphans,
study: studyId,
latest: latest && 100
```

`R.filter` will remove false key.

File: webapp/src/services/api/study.ts [hunk 3]
```diff
@@ -329,19 +330,21 @@ export const mapLaunchJobDTO = (j: LaunchJobDTO): LaunchJob => ({
...
+      study: studyId || "",
+      latest: latest ? "100" : "",
+    }),
+  ).toString();
```
Comment (skamril) [inline webapp/src/services/api/study.ts]: `toString()` useless.

File: webapp/src/services/api/study.ts [hunk 4]
```diff
@@ -329,19 +330,21 @@ export const mapLaunchJobDTO = (j: LaunchJobDTO): LaunchJob => ({
...
+
+  return (await client.get(`/v1/launcher/jobs?${queryParams}`)).data.map(
```
Comment (skamril) [inline webapp/src/services/api/study.ts]: `client.get` can throw an error.

```javascript
return client.get(`/v1/launcher/jobs?${queryParams}`).then(({ data }) => data.map(mapLaunchJobDTO));
```

**Review by skamril — CHANGES_REQUESTED** [review]

File: webapp/src/services/api/study.ts (hunk 3 above)
Comment (hdinia) [reply webapp/src/services/api/study.ts]: no queryParams must be a string

Comment (skamril) [reply webapp/src/services/api/study.ts]: yes but you include it in a string, so automatically `toString()` will be called

**Review by skamril — DISMISSED** [review]

**Review by skamril — APPROVED** [review]
